name: supermetrics

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  app-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@b7d1d9c9a92d8d8463ce36d7f60da34d461724f8
      with:
        php-version: '8.0'
    - uses: actions/checkout@v2
    - name: Copy config
      run: php -r "file_exists('config.php') || copy('config.example.php', 'config.php');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Directory Permissions
      run: chmod -R 777 data
    - name: Show statistics
      run: php command statistics
    - name: Execute tests (Unit and Feature tests)
      run: vendor/bin/pest
